In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [31]:
travel = pd.read_csv('travel.csv')

In [32]:
travel.head()

Age  FrequentFlyer  AnnualIncomeClass  ServicesOpted  \
0   34              0                  1              6   
1   34              1                  0              5   
2   37              0                  1              3   
3   30              0                  1              2   
4   30              0                  0              1   

   AccountSyncedToSocialMedia  BookedHotelOr0t  Target  
0                           0                1       0  
1                           1                0       1  
2                           1                0       0  
3                           0                0       0  
4                           0                0       0

In [33]:
travel.shape

(954, 7)

In [34]:
travel['Target'].value_counts()

0    730
1    224
Name: Target, dtype: int64

In [35]:
X = travel.drop (columns='Target', axis=1)
Y = travel['Target']

In [23]:
print(X)

     Age  FrequentFlyer  AnnualIncomeClass  ServicesOpted  \
0     34              0                  1              6   
1     34              1                  0              5   
2     37              0                  1              3   
3     30              0                  1              2   
4     30              0                  0              1   
..   ...            ...                ...            ...   
949   31              1                  0              1   
950   30              0                  1              5   
951   37              0                  1              4   
952   30              0                  0              1   
953   31              1                  2              1   

     AccountSyncedToSocialMedia  BookedHotelOr0t  
0                             0                1  
1                             1                0  
2                             1                0  
3                             0                0  
4           

In [24]:
print(Y)

0      0
1      1
2      0
3      0
4      0
      ..
949    0
950    0
951    0
952    0
953    0
Name: Target, Length: 954, dtype: int64


In [25]:
scaler = StandardScaler()

In [26]:
scaler.fit(X)

StandardScaler()

In [15]:
print(Y)

0      0
1      1
2      0
3      0
4      0
      ..
949    0
950    0
951    0
952    0
953    0
Name: Target, Length: 954, dtype: int64


In [27]:
standarized_data = scaler.transform(X)

In [28]:
print(standarized_data)

[[ 0.56690365 -0.65432692  0.33167822  2.21932995 -0.77849894  1.2344268 ]
 [ 0.56690365  1.52828804 -1.06224698  1.59642887  1.28452326 -0.81009259]
 [ 1.46628183 -0.65432692  0.33167822  0.35062671  1.28452326 -0.81009259]
 ...
 [ 1.46628183 -0.65432692  0.33167822  0.97352779 -0.77849894 -0.81009259]
 [-0.63226726 -0.65432692 -1.06224698 -0.89517545  1.28452326  1.2344268 ]
 [-0.33247453  1.52828804  1.72560341 -0.89517545 -0.77849894 -0.81009259]]


In [36]:
X = standarized_data
Y = travel['Target']

In [37]:
print(X)
print(Y)

[[ 0.56690365 -0.65432692  0.33167822  2.21932995 -0.77849894  1.2344268 ]
 [ 0.56690365  1.52828804 -1.06224698  1.59642887  1.28452326 -0.81009259]
 [ 1.46628183 -0.65432692  0.33167822  0.35062671  1.28452326 -0.81009259]
 ...
 [ 1.46628183 -0.65432692  0.33167822  0.97352779 -0.77849894 -0.81009259]
 [-0.63226726 -0.65432692 -1.06224698 -0.89517545  1.28452326  1.2344268 ]
 [-0.33247453  1.52828804  1.72560341 -0.89517545 -0.77849894 -0.81009259]]
0      0
1      1
2      0
3      0
4      0
      ..
949    0
950    0
951    0
952    0
953    0
Name: Target, Length: 954, dtype: int64


In [38]:
X_train, X_test, Y_train, Y_tes = train_test_split(X, Y, test_size= 0.2, stratify=Y, random_state=2)

In [39]:
print(X.shape, X_train.shape, X_test.shape)

(954, 6) (763, 6) (191, 6)


In [40]:
classifier = svm.SVC(kernel='linear')

In [41]:
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

In [42]:
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [43]:
print('Akurasi data training adalah = ', training_data_accuracy)

Akurasi data training adalah =  0.8191349934469201


In [46]:
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_tes)

In [47]:
print('Akurasi data testing adalah = ', test_data_accuracy)

Akurasi data testing adalah =  0.8272251308900523


In [51]:
input_data = (34,1,0,5,1,0)

input_data_as_numpy_array = np.array(input_data)

input_data_reshape = input_data_as_numpy_array.reshape(1, -1)

std_data = scaler.transform(input_data_reshape)
print(std_data)

prediction = classifier.predict(std_data)
print(prediction)

if (prediction[0] == 0):
    print ('Customer bukan target')
else :
    print('Customer adalah target')

[[ 0.56690365  1.52828804 -1.06224698  1.59642887  1.28452326 -0.81009259]]
[1]
Customer adalah target


c:\Users\ciloe\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [52]:
import pickle

In [53]:
filename = 'travel_model.sav'
pickle.dump(classifier, open(filename,'wb'))